function tresEnRaya(){
    this.partida = function(){
      document.getElementById("1").addEventListener("click",function(){if(document.getElementById("1").innerHTML !== "O" || document.getElementById("2").innerHTML !== "O" || document.getElementById("3").innerHTML !== "O" || document.getElementById("4").innerHTML !== "O" || document.getElementById("5").innerHTML !== "O" || document.getElementById("6").innerHTML !== "O" || document.getElementById("7").innerHTML !== "O" || document.getElementById("8").innerHTML !== "O" || document.getElementById("9").innerHTML !== "O"){document.getElementById("1").innerHTML = "<b><big>X</big></b>";}if(document.getElementById("1").innerHTML !== "X" || document.getElementById("2").innerHTML !== "X" || document.getElementById("3").innerHTML !== "X" || document.getElementById("4").innerHTML !== "X" || document.getElementById("5").innerHTML !== "X" || document.getElementById("6").innerHTML !== "X" || document.getElementById("7").innerHTML !== "X" || document.getElementById("8").innerHTML !== "X" || document.getElementById("9").innerHTML !== "X"){document.getElementById(Math.round(Math.random()*9)+1).innerHTML = "<b><big>O</big></b>";}});
      document.getElementById("2").addEventListener("click",function(){if(document.getElementById("1").innerHTML !== "O" || document.getElementById("2").innerHTML !== "O" || document.getElementById("3").innerHTML !== "O" || document.getElementById("4").innerHTML !== "O" || document.getElementById("5").innerHTML !== "O" || document.getElementById("6").innerHTML !== "O" || document.getElementById("7").innerHTML !== "O" || document.getElementById("8").innerHTML !== "O" || document.getElementById("9").innerHTML !== "O"){document.getElementById("2").innerHTML = "<b><big>X</big></b>";}if(document.getElementById("1").innerHTML !== "X" || document.getElementById("2").innerHTML !== "X" || document.getElementById("3").innerHTML !== "X" || document.getElementById("4").innerHTML !== "X" || document.getElementById("5").innerHTML !== "X" || document.getElementById("6").innerHTML !== "X" || document.getElementById("7").innerHTML !== "X" || document.getElementById("8").innerHTML !== "X" || document.getElementById("9").innerHTML !== "X"){document.getElementById(Math.round(Math.random()*9)+1).innerHTML = "<b><big>O</big></b>";}});
      document.getElementById("3").addEventListener("click",function(){if(document.getElementById("1").innerHTML !== "O" || document.getElementById("2").innerHTML !== "O" || document.getElementById("3").innerHTML !== "O" || document.getElementById("4").innerHTML !== "O" || document.getElementById("5").innerHTML !== "O" || document.getElementById("6").innerHTML !== "O" || document.getElementById("7").innerHTML !== "O" || document.getElementById("8").innerHTML !== "O" || document.getElementById("9").innerHTML !== "O"){document.getElementById("3").innerHTML = "<b><big>X</big></b>";}if(document.getElementById("1").innerHTML !== "X" || document.getElementById("2").innerHTML !== "X" || document.getElementById("3").innerHTML !== "X" || document.getElementById("4").innerHTML !== "X" || document.getElementById("5").innerHTML !== "X" || document.getElementById("6").innerHTML !== "X" || document.getElementById("7").innerHTML !== "X" || document.getElementById("8").innerHTML !== "X" || document.getElementById("9").innerHTML !== "X"){document.getElementById(Math.round(Math.random()*9)+1).innerHTML = "<b><big>O</big></b>";}});
      document.getElementById("4").addEventListener("click",function(){if(document.getElementById("1").innerHTML !== "O" || document.getElementById("2").innerHTML !== "O" || document.getElementById("3").innerHTML !== "O" || document.getElementById("4").innerHTML !== "O" || document.getElementById("5").innerHTML !== "O" || document.getElementById("6").innerHTML !== "O" || document.getElementById("7").innerHTML !== "O" || document.getElementById("8").innerHTML !== "O" || document.getElementById("9").innerHTML !== "O"){document.getElementById("4").innerHTML = "<b><big>X</big></b>";}if(document.getElementById("1").innerHTML !== "X" || document.getElementById("2").innerHTML !== "X" || document.getElementById("3").innerHTML !== "X" || document.getElementById("4").innerHTML !== "X" || document.getElementById("5").innerHTML !== "X" || document.getElementById("6").innerHTML !== "X" || document.getElementById("7").innerHTML !== "X" || document.getElementById("8").innerHTML !== "X" || document.getElementById("9").innerHTML !== "X"){document.getElementById(Math.round(Math.random()*9)+1).innerHTML = "<b><big>O</big></b>";}});
      document.getElementById("5").addEventListener("click",function(){if(document.getElementById("1").innerHTML !== "O" || document.getElementById("2").innerHTML !== "O" || document.getElementById("3").innerHTML !== "O" || document.getElementById("4").innerHTML !== "O" || document.getElementById("5").innerHTML !== "O" || document.getElementById("6").innerHTML !== "O" || document.getElementById("7").innerHTML !== "O" || document.getElementById("8").innerHTML !== "O" || document.getElementById("9").innerHTML !== "O"){document.getElementById("5").innerHTML = "<b><big>X</big></b>";}if(document.getElementById("1").innerHTML !== "X" || document.getElementById("2").innerHTML !== "X" || document.getElementById("3").innerHTML !== "X" || document.getElementById("4").innerHTML !== "X" || document.getElementById("5").innerHTML !== "X" || document.getElementById("6").innerHTML !== "X" || document.getElementById("7").innerHTML !== "X" || document.getElementById("8").innerHTML !== "X" || document.getElementById("9").innerHTML !== "X"){document.getElementById(Math.round(Math.random()*9)+1).innerHTML = "<b><big>O</big></b>";}});
      document.getElementById("6").addEventListener("click",function(){if(document.getElementById("1").innerHTML !== "O" || document.getElementById("2").innerHTML !== "O" || document.getElementById("3").innerHTML !== "O" || document.getElementById("4").innerHTML !== "O" || document.getElementById("5").innerHTML !== "O" || document.getElementById("6").innerHTML !== "O" || document.getElementById("7").innerHTML !== "O" || document.getElementById("8").innerHTML !== "O" || document.getElementById("9").innerHTML !== "O"){document.getElementById("6").innerHTML = "<b><big>X</big></b>";}if(document.getElementById("1").innerHTML !== "X" || document.getElementById("2").innerHTML !== "X" || document.getElementById("3").innerHTML !== "X" || document.getElementById("4").innerHTML !== "X" || document.getElementById("5").innerHTML !== "X" || document.getElementById("6").innerHTML !== "X" || document.getElementById("7").innerHTML !== "X" || document.getElementById("8").innerHTML !== "X" || document.getElementById("9").innerHTML !== "X"){document.getElementById(Math.round(Math.random()*9)+1).innerHTML = "<b><big>O</big></b>";}});
      document.getElementById("7").addEventListener("click",function(){if(document.getElementById("1").innerHTML !== "O" || document.getElementById("2").innerHTML !== "O" || document.getElementById("3").innerHTML !== "O" || document.getElementById("4").innerHTML !== "O" || document.getElementById("5").innerHTML !== "O" || document.getElementById("6").innerHTML !== "O" || document.getElementById("7").innerHTML !== "O" || document.getElementById("8").innerHTML !== "O" || document.getElementById("9").innerHTML !== "O"){document.getElementById("7").innerHTML = "<b><big>X</big></b>";}if(document.getElementById("1").innerHTML !== "X" || document.getElementById("2").innerHTML !== "X" || document.getElementById("3").innerHTML !== "X" || document.getElementById("4").innerHTML !== "X" || document.getElementById("5").innerHTML !== "X" || document.getElementById("6").innerHTML !== "X" || document.getElementById("7").innerHTML !== "X" || document.getElementById("8").innerHTML !== "X" || document.getElementById("9").innerHTML !== "X"){document.getElementById(Math.round(Math.random()*9)+1).innerHTML = "<b><big>O</big></b>";}});
      document.getElementById("8").addEventListener("click",function(){if(document.getElementById("1").innerHTML !== "O" || document.getElementById("2").innerHTML !== "O" || document.getElementById("3").innerHTML !== "O" || document.getElementById("4").innerHTML !== "O" || document.getElementById("5").innerHTML !== "O" || document.getElementById("6").innerHTML !== "O" || document.getElementById("7").innerHTML !== "O" || document.getElementById("8").innerHTML !== "O" || document.getElementById("9").innerHTML !== "O"){document.getElementById("8").innerHTML = "<b><big>X</big></b>";}if(document.getElementById("1").innerHTML !== "X" || document.getElementById("2").innerHTML !== "X" || document.getElementById("3").innerHTML !== "X" || document.getElementById("4").innerHTML !== "X" || document.getElementById("5").innerHTML !== "X" || document.getElementById("6").innerHTML !== "X" || document.getElementById("7").innerHTML !== "X" || document.getElementById("8").innerHTML !== "X" || document.getElementById("9").innerHTML !== "X"){document.getElementById(Math.round(Math.random()*9)+1).innerHTML = "<b><big>O</big></b>";}});
      document.getElementById("9").addEventListener("click",function(){if(document.getElementById("1").innerHTML !== "O" || document.getElementById("2").innerHTML !== "O" || document.getElementById("3").innerHTML !== "O" || document.getElementById("4").innerHTML !== "O" || document.getElementById("5").innerHTML !== "O" || document.getElementById("6").innerHTML !== "O" || document.getElementById("7").innerHTML !== "O" || document.getElementById("8").innerHTML !== "O" || document.getElementById("9").innerHTML !== "O"){document.getElementById("9").innerHTML = "<b><big>X</big></b>";}if(document.getElementById("1").innerHTML !== "X" || document.getElementById("2").innerHTML !== "X" || document.getElementById("3").innerHTML !== "X" || document.getElementById("4").innerHTML !== "X" || document.getElementById("5").innerHTML !== "X" || document.getElementById("6").innerHTML !== "X" || document.getElementById("7").innerHTML !== "X" || document.getElementById("8").innerHTML !== "X" || document.getElementById("9").innerHTML !== "X"){document.getElementById(Math.round(Math.random()*9)+1).innerHTML = "<b><big>O</big></b>";}});
    };
    
    this.ganador = function(){
       var uno = document.getElementById("1");
       var dos = document.getElementById("2");
       var tres = document.getElementById("3");
       var cuatro = document.getElementById("4");
       var cinco = document.getElementById("5");
       var seis = document.getElementById("6");
       var siete = document.getElementById("7");
       var ocho = document.getElementById("8");
       var nueve = document.getElementById("9");
       var resultado = "";
       
       if((uno.innerHTML == "X" && dos.innerHTML == "X" && tres.innerHTML == "X") || (cuatro.innerHTML == "X" && cinco.innerHTML == "X" && seis.innerHTML == "X") || (siete.innerHTML == "X" && ocho.innerHTML == "X" && nueve.innerHTML == "X") || (uno.innerHTML == "X" && cuatro.innerHTML == "X" && siete.innerHTML == "X") || (dos.innerHTML == "X" && cinco.innerHTML == "X" && ocho.innerHTML == "X") || (tres.innerHTML == "X" && seis.innerHTML == "X" && nueve.innerHTML == "X") || (uno.innerHTML == "X" && cinco.innerHTML == "X" && nueve.innerHTML == "X") || (tres.innerHTML == "X" && cinco.innerHTML == "X" && siete.innerHTML == "X")){
         resultado = "El ganador es el humano";  
       }else if((uno.innerHTML == "O" && dos.innerHTML == "O" && tres.innerHTML == "O") || (cuatro.innerHTML == "O" && cinco.innerHTML == "O" && seis.innerHTML == "O") || (siete.innerHTML == "O" && ocho.innerHTML == "O" && nueve.innerHTML == "O") || (uno.innerHTML == "O" && cuatro.innerHTML == "O" && siete.innerHTML == "O") || (dos.innerHTML == "O" && cinco.innerHTML == "O" && ocho.innerHTML == "O") || (tres.innerHTML == "O" && seis.innerHTML == "O" && nueve.innerHTML == "O") || (uno.innerHTML == "O" && cinco.innerHTML == "O" && nueve.innerHTML == "O") || (tres.innerHTML == "O" && cinco.innerHTML == "O" && siete.innerHTML == "O")){
         resultado = "El ganador es la maquina";           
       }else if(((uno.innerHTML == "X" && dos.innerHTML == "X" && tres.innerHTML == "X") || (cuatro.innerHTML == "X" && cinco.innerHTML == "X" && seis.innerHTML == "X") || (siete.innerHTML == "X" && ocho.innerHTML == "X" && nueve.innerHTML == "X") || (uno.innerHTML == "X" && cuatro.innerHTML == "X" && siete.innerHTML == "X") || (dos.innerHTML == "X" && cinco.innerHTML == "X" && ocho.innerHTML == "X") || (tres.innerHTML == "X" && seis.innerHTML == "X" && nueve.innerHTML == "X") || (uno.innerHTML == "X" && cinco.innerHTML == "X" && nueve.innerHTML == "X") || (tres.innerHTML == "X" && cinco.innerHTML == "X" && siete.innerHTML == "X")) && (uno.innerHTML == "O" && dos.innerHTML == "O" && tres.innerHTML == "O") || (cuatro.innerHTML == "O" && cinco.innerHTML == "O" && seis.innerHTML == "O") || (siete.innerHTML == "O" && ocho.innerHTML == "O" && nueve.innerHTML == "O") || (uno.innerHTML == "O" && cuatro.innerHTML == "O" && siete.innerHTML == "O") || (dos.innerHTML == "O" && cinco.innerHTML == "O" && ocho.innerHTML == "O") || (tres.innerHTML == "O" && seis.innerHTML == "O" && nueve.innerHTML == "O") || (uno.innerHTML == "O" && cinco.innerHTML == "O" && nueve.innerHTML == "O") || (tres.innerHTML == "O" && cinco.innerHTML == "O" && siete.innerHTML == "O")){
           resultado = "Empate";
       }else{
           resultado = "No ha ganado nadie";
       }
       return resultado;
    };
    
    this.terminar = function(){
       var uno = document.getElementById("1");
       var dos = document.getElementById("2");
       var tres = document.getElementById("3");
       var cuatro = document.getElementById("4");
       var cinco = document.getElementById("5");
       var seis = document.getElementById("6");
       var siete = document.getElementById("7");
       var ocho = document.getElementById("8");
       var nueve = document.getElementById("9");
       var resultado = "";
       var contadorX = 0;
       var contadorO = 0;
       if(uno.innerHTML == "X" || dos.innerHTML == "X" || tres.innerHTML == "X" || cuatro.innerHTML == "X" || cinco.innerHTML == "X" || seis.innerHTML == "X" || siete.innerHTML == "X" || ocho.innerHTML == "X" || nueve.innerHTML == "X"){
         contadorX++;  
       }else if(uno.innerHTML == "O" || dos.innerHTML == "O" || tres.innerHTML == "O" || cuatro.innerHTML == "O" || cinco.innerHTML == "O" || seis.innerHTML == "O" || siete.innerHTML == "O" || ocho.innerHTML == "O" || nueve.innerHTML == "O"){
         contadorO++;  
       }
       if(contadorX == 3){
           resultado = "Ha terminado el juego";
       }else if(contadorO == 3){
           resultado = "Ha terminado el juego";
       }
       return resultado;
    };
}

var juego = new tresEnRaya();
juego.partida();
document.getElementById("quienGana").innerHTML = juego.ganador();
document.getElementById("quienGana").innerHTML += "<br>"+juego.terminar();
